<?php
 return array (
'placeholder_join_free_courses' => 'Join Free courses',
'title_courses_categories' => 'Courses Categories',
'title_most_popular_certificates' => 'Most Popular Certificates',
'title_everything_online' => 'Everything Online',
'title_trusted_training' => 'Trusted Training Centersdddddd',
'title_500k_courses' => '500K Courses',
'title_145_companies' => '145+ Companies',
'title_million_learners' => 'Million Learners',
'title_million_trainers' => 'Million Trainers',
'title_courses' => 'Courses',
'title_companies' => 'Companies',
'title_learn_at_your_place' => 'LEARN AT YOUR OWN PACE',
'title_most_popular_courses' => 'Most Popular Courses',
'title_feedback' => 'Feedback',
'title_our_testimonials' => 'Our Testimonials',
'title_training_centers' => 'Training Centers',
'title_register_training_centers' => 'Register as Training Center',
'title_register_as_company' => 'Register as Company',
'content_everything_online' => 'Free online courses from the world’s leading experts. Join 13 million learners today.',
'content_trusted_training' => 'Free online courses from the world’s leading experts. Join 13 million learners today.',
'content_500k_courses' => 'Free online courses from the world’s leading experts. Join 13 million learners today.',
'content_145_companies' => 'Free online courses from the world’s leading experts. Join 13 million learners today.',
'content_most_popular_courses' => 'Explore all of our courses and pick your suitable ones to enroll and start learning with us! We ensure that you will never regret it!',
'content_register_as_individual_user' => 'Enjoy the top notch learning methods and achieve next level skills! You are the creator of your own career & we will guide you through that. <a href="#!" id="myBtn8">Register as Individual User!</a>.',
'content_register_training_centers' => 'Choose from hundreds of free courses, or get a degree or certificate at a breakthrough price. Learn at your own pace.',
'content_register_as_company' => 'Choose from hundreds of free courses, or get a degree or certificate at a breakthrough price. Learn at your own pace.',
'btn_explore' => 'Explore',
'btn_view_all' => 'View All',
'btn_learn_more' => 'Learn More',
'btn_register' => 'Register',
'btn_read_more' => 'Read More',
);